// ============================================================
// MES360° — engineering drawings, generated from the live system
// ------------------------------------------------------------
// Tracker IDs 25 and 26: the production-line instrumentation layout and the
// automation system architecture.
//
// Generated from `machines`, `devices` and `tag_definitions` rather than drawn
// by hand. A hand-drawn diagram is out of date the first time somebody re-binds
// a tag, and then it is worse than no diagram: it is a document that says the
// wrong thing with authority. Re-run this after any I/O change.
//
//   npx ts-node --transpile-only prisma/generate-engineering-drawings.ts
//   DATABASE_URL="…/mes360…" FACTORY=SDPF npx ts-node …   # pick the factory
//
// Output: docs/NCC-25-Instrumentation-Layout.html
//         docs/NCC-26-Automation-Architecture.html
// ============================================================

import { PrismaClient } from '@prisma/client';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const prisma = new PrismaClient();
const FACTORY_CODE = process.env.FACTORY || 'SDPF';
const OUT_DIR = join(__dirname, '..', '..', '..', 'docs');

const esc = (s: unknown) =>
  String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]!));

/** Shared page chrome — printable A4, self-contained, no external assets. */
function page(title: string, subtitle: string, body: string, generatedAt: Date): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
  :root {
    --bg: #ffffff; --fg: #14201f; --muted: #5d6f6d; --line: #d7e0de;
    --accent: #0f766e; --accent-soft: #ecf7f5; --warn: #b45309; --warn-soft: #fef6e7;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--fg);
         font: 14px/1.6 "Segoe UI", system-ui, -apple-system, sans-serif; }
  .sheet { max-width: 1040px; margin: 0 auto; padding: 32px 36px 64px; }
  header.doc { border-bottom: 3px solid var(--accent); padding-bottom: 14px; margin-bottom: 24px; }
  header.doc h1 { margin: 0 0 4px; font-size: 24px; letter-spacing: -0.01em; }
  header.doc .sub { color: var(--muted); font-size: 13px; }
  header.doc .meta { margin-top: 10px; font-size: 12px; color: var(--muted); }
  h2 { font-size: 15px; text-transform: uppercase; letter-spacing: 0.06em;
       color: var(--accent); margin: 32px 0 12px; }
  h3 { font-size: 14px; margin: 22px 0 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 12.5px; margin: 10px 0 18px; }
  th, td { border: 1px solid var(--line); padding: 6px 9px; text-align: left; vertical-align: top; }
  th { background: var(--accent-soft); font-weight: 600; }
  code, .mono { font-family: "Cascadia Mono", Consolas, monospace; font-size: 12px; }
  .note { border-left: 3px solid var(--accent); background: var(--accent-soft);
          padding: 10px 14px; margin: 14px 0; font-size: 13px; }
  .warn { border-left-color: var(--warn); background: var(--warn-soft); }
  .tag { display: inline-block; padding: 1px 7px; border-radius: 10px; font-size: 11px;
         background: var(--accent-soft); border: 1px solid var(--line); }
  svg { max-width: 100%; height: auto; }
  .scroll { overflow-x: auto; }
  footer { margin-top: 40px; padding-top: 14px; border-top: 1px solid var(--line);
           font-size: 11.5px; color: var(--muted); }
  @media print {
    .sheet { max-width: none; padding: 0; }
    h2 { break-after: avoid; } table { break-inside: auto; } tr { break-inside: avoid; }
  }
</style>
</head>
<body>
<div class="sheet">
<header class="doc">
  <h1>${esc(title)}</h1>
  <div class="sub">${esc(subtitle)}</div>
  <div class="meta">NCC · ${esc(FACTORY_CODE)} · generated from the live configuration on
    ${generatedAt.toISOString().slice(0, 16).replace('T', ' ')} UTC</div>
</header>
${body}
<footer>
  Generated by <code>prisma/generate-engineering-drawings.ts</code> directly from
  <code>machines</code>, <code>devices</code> and <code>tag_definitions</code>. It describes what the
  system is actually bound to, not what was intended. Re-run it after any I/O change.
</footer>
</div>
</body>
</html>`;
}

interface TagRow {
  code: string; name: string; tagType: string; dataType: string;
  counterRole: string | null; signalRole: string | null; energyRole: string | null;
  registerType: string | null; address: string | null; unit: string | null;
  machineCode: string | null; deviceName: string | null; deviceCode: string | null;
}

async function load() {
  const factory = await prisma.factory.findFirst({
    where: { code: FACTORY_CODE },
    select: { id: true, code: true, name: true },
  });
  if (!factory) throw new Error(`No factory with code ${FACTORY_CODE}`);

  const machines = await prisma.machine.findMany({
    where: { factoryId: factory.id, isActive: true, archivedAt: null },
    select: {
      id: true, code: true, name: true, sortOrder: true,
      line: { select: { name: true, code: true, area: { select: { name: true } } } },
    },
    orderBy: { sortOrder: 'asc' },
  });

  const devices = await prisma.device.findMany({
    where: { factoryId: factory.id },
    select: {
      id: true, deviceCode: true, name: true, protocol: true, ipAddress: true,
      port: true, serialPort: true, baudRate: true, unitId: true, isActive: true,
    },
    orderBy: { name: 'asc' },
  });

  const tagRows = await prisma.tagDefinition.findMany({
    where: { factoryId: factory.id, isActive: true },
    select: {
      code: true, name: true, tagType: true, dataType: true, counterRole: true,
      signalRole: true, energyRole: true, registerType: true, address: true, unit: true,
      machine: { select: { code: true } },
      device: { select: { name: true, deviceCode: true } },
    },
  });

  const tags: TagRow[] = tagRows.map((t) => ({
    code: t.code, name: t.name, tagType: String(t.tagType), dataType: String(t.dataType),
    counterRole: t.counterRole ? String(t.counterRole) : null,
    signalRole: t.signalRole ?? null,
    energyRole: t.energyRole ? String(t.energyRole) : null,
    registerType: t.registerType ? String(t.registerType) : null,
    address: t.address ?? null, unit: t.unit ?? null,
    machineCode: t.machine?.code ?? null,
    deviceName: t.device?.name ?? null, deviceCode: t.device?.deviceCode ?? null,
  }));

  return { factory, machines, devices, tags };
}

/**
 * Physical inputs read by more than one machine.
 *
 * On this line the same contact feeds two machines — the filler's output IS the
 * checkweigher's input, so one pulse is counted for both. A drawing that hides
 * that is not a simplification, it is wrong: an engineer tracing a fault would
 * look for a second sensor that does not exist.
 */
function sharedInputs(tags: TagRow[]) {
  const byPoint = new Map<string, TagRow[]>();
  for (const t of tags) {
    if (!t.deviceCode || t.address === null || !t.registerType) continue;
    const key = `${t.deviceCode}|${t.registerType}|${t.address}`;
    byPoint.set(key, [...(byPoint.get(key) ?? []), t]);
  }
  return [...byPoint.entries()]
    .map(([key, list]) => ({ key, list, machines: [...new Set(list.map((t) => t.machineCode).filter(Boolean))] }))
    .filter((p) => p.machines.length > 1);
}

const fmtAddress = (t: TagRow) =>
  t.registerType === 'DISCRETE' ? `DI ${t.address}`
  : t.registerType === 'COIL' ? `DO ${t.address}`
  : `${t.registerType ?? ''} ${t.address ?? ''}`.trim();

// ────────────────────────────────────────────────────────────
// ID 25 — instrumentation layout
// ────────────────────────────────────────────────────────────
function instrumentationLayout(data: Awaited<ReturnType<typeof load>>, now: Date): string {
  const { machines, devices, tags } = data;
  const shared = sharedInputs(tags);
  const line = machines[0]?.line;

  // Line diagram: one box per machine in material-flow order, with the I/O
  // points bound to it underneath.
  const boxW = 168, gap = 34, boxH = 74, top = 46;
  const svgW = machines.length * boxW + (machines.length - 1) * gap + 20;
  const boxes = machines.map((m, i) => {
    const x = 10 + i * (boxW + gap);
    const io = tags.filter((t) => t.machineCode === m.code && t.registerType === 'DISCRETE');
    const counters = io.filter((t) => t.tagType === 'COUNTER').length;
    const signals = io.filter((t) => t.tagType === 'STATUS').length;
    const energy = tags.filter((t) => t.machineCode === m.code && t.tagType === 'ENERGY').length;
    const arrow = i < machines.length - 1
      ? `<line x1="${x + boxW}" y1="${top + boxH / 2}" x2="${x + boxW + gap - 6}" y2="${top + boxH / 2}"
             stroke="#0f766e" stroke-width="2" marker-end="url(#a)"/>`
      : '';
    return `
      <g>
        <rect x="${x}" y="${top}" width="${boxW}" height="${boxH}" rx="8"
              fill="#ecf7f5" stroke="#0f766e" stroke-width="1.5"/>
        <text x="${x + boxW / 2}" y="${top + 22}" text-anchor="middle" font-size="13" font-weight="700">${esc(m.code)}</text>
        <text x="${x + boxW / 2}" y="${top + 40}" text-anchor="middle" font-size="11.5">${esc(m.name)}</text>
        <text x="${x + boxW / 2}" y="${top + 60}" text-anchor="middle" font-size="10.5" fill="#5d6f6d">${counters} counter · ${signals} status · ${energy} energy</text>
      </g>${arrow}`;
  }).join('');

  const machineRows = machines.map((m) => {
    const mt = tags.filter((t) => t.machineCode === m.code);
    const describe = (t: TagRow) =>
      `<code>${esc(t.code)}</code> <span class="tag">${esc(t.counterRole ?? t.signalRole ?? t.energyRole ?? t.tagType)}</span> <span class="mono">${esc(fmtAddress(t))}</span>`;
    const counters = mt.filter((t) => t.tagType === 'COUNTER');
    const status = mt.filter((t) => t.tagType === 'STATUS');
    const energy = mt.filter((t) => t.tagType === 'ENERGY');
    return `<tr>
      <td class="mono"><b>${esc(m.code)}</b><br>${esc(m.name)}</td>
      <td>${counters.map(describe).join('<br>') || '—'}</td>
      <td>${status.map(describe).join('<br>') || '—'}</td>
      <td>${energy.length ? `${energy.length} register(s) · ${esc([...new Set(energy.map((t) => t.deviceName))].join(', '))}` : '—'}</td>
    </tr>`;
  }).join('');

  const deviceRows = devices.filter((d) => d.isActive !== false).map((d) => {
    const bound = tags.filter((t) => t.deviceCode === d.deviceCode).length;
    const conn = d.protocol === 'MODBUS_RTU'
      ? `${esc(d.serialPort ?? '—')} @ ${esc(d.baudRate ?? '—')} baud, unit ${esc(d.unitId)}`
      : `${esc(d.ipAddress ?? '—')}:${esc(d.port ?? '—')}, unit ${esc(d.unitId)}`;
    return `<tr><td class="mono">${esc(d.deviceCode)}</td><td>${esc(d.name)}</td>
      <td><span class="tag">${esc(d.protocol)}</span></td><td class="mono">${conn}</td><td>${bound}</td></tr>`;
  }).join('');

  const sharedBlock = shared.length === 0 ? '' : `
    <div class="note warn">
      <b>Shared physical inputs — ${shared.length} point(s).</b> These contacts are read by more than one
      machine. One pulse increments both counters, by design: the upstream machine's output is the
      downstream machine's input, and there is no second sensor. An engineer tracing a fault must know
      this, so it is stated here rather than hidden behind a tidier drawing.
      <table>
        <thead><tr><th>Device</th><th>Point</th><th>Machines</th><th>Bound tags</th></tr></thead>
        <tbody>${shared.map((p) => {
          const [dev, reg, addr] = p.key.split('|');
          const point = reg === 'DISCRETE' ? `DI ${addr}` : `${reg} ${addr}`;
          return `<tr><td class="mono">${esc(dev)}</td><td class="mono">${esc(point)}</td>
            <td>${esc(p.machines.join(' + '))}</td>
            <td class="mono">${p.list.map((t) => esc(t.code)).join('<br>')}</td></tr>`;
        }).join('')}</tbody>
      </table>
    </div>`;

  const body = `
<h2>1 · Line</h2>
<p>${esc(line?.area?.name ?? '')} → <b>${esc(line?.name ?? '')}</b> (${esc(line?.code ?? '')}) —
${machines.length} machines in material-flow order.</p>
<div class="scroll">
<svg viewBox="0 0 ${svgW} ${top + boxH + 24}" width="${svgW}" role="img"
     aria-label="Machines in material-flow order">
  <defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto">
    <path d="M0 0 L10 5 L0 10 z" fill="#0f766e"/></marker></defs>
  <text x="10" y="22" font-size="12" fill="#5d6f6d">Material flow →</text>
  ${boxes}
</svg>
</div>

<h2>2 · Instrumentation per machine</h2>
<table>
  <thead><tr><th style="width:20%">Machine</th><th style="width:30%">Counting</th>
    <th style="width:30%">Status signals</th><th style="width:20%">Energy</th></tr></thead>
  <tbody>${machineRows}</tbody>
</table>
${sharedBlock}

<h2>3 · Field devices</h2>
<table>
  <thead><tr><th>Code</th><th>Name</th><th>Protocol</th><th>Connection</th><th>Tags</th></tr></thead>
  <tbody>${deviceRows}</tbody>
</table>

<h2>4 · How a signal is read</h2>
<p>Every status point is a <b>discrete input</b> — a boolean contact, not a status word. That follows
NCC's I/O specification: the remote I/O modules provide 8 digital inputs each, and the meaning of each
input is declared per tag rather than compiled in:</p>
<table>
  <thead><tr><th>Signal role</th><th>Meaning</th></tr></thead>
  <tbody>
    <tr><td class="mono">RUN_MODE</td><td>ON = running <i>or</i> ready with nothing to process. It does
      not by itself distinguish working from waiting.</td></tr>
    <tr><td class="mono">RUN_MODE_PULSED</td><td>Steady ON = running, <b>pulsing</b> = stopped, OFF = alarm.
      Judged by how often the bit changes, not by its level.</td></tr>
    <tr><td class="mono">PROCESSING</td><td>Product is actually being worked. This is what separates a
      machine that is producing from one that is merely ready — see document 26.</td></tr>
    <tr><td class="mono">INFEED_AVAILABLE / OUTFEED_BLOCKED</td><td>Material-flow signals. A measurement
      here always outranks inference from neighbouring machines.</td></tr>
  </tbody>
</table>
<div class="note">All of the above — the role, the pulse window, the idle threshold, and what each
resulting state costs in downtime and OEE — is edited in the application (<b>IoT → Signal Rules</b>) or
on the edge gateway's own dashboard. None of it requires a new build.</div>`;

  return page(
    'Production Line Instrumentation Layout',
    'Tracker ID 25 · every instrument, its device, its address and what it means',
    body, now,
  );
}

// ────────────────────────────────────────────────────────────
// ID 26 — automation architecture
// ────────────────────────────────────────────────────────────
function automationArchitecture(data: Awaited<ReturnType<typeof load>>, now: Date): string {
  const { machines, devices, tags } = data;
  const counters = tags.filter((t) => t.tagType === 'COUNTER').length;
  const status = tags.filter((t) => t.tagType === 'STATUS').length;
  const energy = tags.filter((t) => t.tagType === 'ENERGY').length;
  const meters = devices.filter((d) => d.name.includes('meter')).length;
  const io = devices.filter((d) => !d.name.includes('meter') && d.isActive !== false).length;

  const levels = [
    { id: 'L0', title: 'Field', detail: `${machines.length} machines · sensors and contacts · ${meters} power meter(s)` },
    { id: 'L1', title: 'Control & I/O', detail: `${io} Modbus device(s) — remote I/O modules (8 DI each) and meters over TCP and RTU` },
    { id: 'L2', title: 'Edge Gateway', detail: 'Polls at 100 ms · counts locally · derives machine state · evaluates alarms · buffers through an outage' },
    { id: 'L3', title: 'MES services', detail: 'Production, OEE, downtime, quality, energy · fact store of per-minute snapshots' },
    { id: 'L4', title: 'Business', detail: 'Dashboards, reports, ERP / SAP integration' },
  ];
  const rowH = 62, w = 940;
  const pyramid = levels.map((l, i) => {
    const y = 12 + i * (rowH + 10);
    return `
      <g>
        <rect x="10" y="${y}" width="${w - 20}" height="${rowH}" rx="8"
              fill="${i === 2 ? '#0f766e' : '#ecf7f5'}" stroke="#0f766e" stroke-width="1.5"/>
        <text x="30" y="${y + 26}" font-size="13" font-weight="700"
              fill="${i === 2 ? '#ffffff' : '#14201f'}">${l.id} · ${esc(l.title)}</text>
        <text x="30" y="${y + 46}" font-size="11.5"
              fill="${i === 2 ? '#d7f0ec' : '#5d6f6d'}">${esc(l.detail)}</text>
      </g>`;
  }).join('');

  const body = `
<h2>1 · Layers</h2>
<div class="scroll">
<svg viewBox="0 0 ${w} ${12 + levels.length * (rowH + 10)}" width="${w}" role="img"
     aria-label="Automation layers L0 to L4">${pyramid}</svg>
</div>

<h2>2 · What is bound today</h2>
<table>
  <thead><tr><th>Layer</th><th>Component</th><th>Count</th><th>Notes</th></tr></thead>
  <tbody>
    <tr><td>L0</td><td>Machines</td><td>${machines.length}</td><td>${esc(machines.map((m) => m.code).join(', '))}</td></tr>
    <tr><td>L1</td><td>Modbus devices</td><td>${devices.filter((d) => d.isActive !== false).length}</td><td>TCP and RTU</td></tr>
    <tr><td>L1</td><td>Counting inputs</td><td>${counters}</td><td>Discrete, edge-counted at the gateway</td></tr>
    <tr><td>L1</td><td>Status inputs</td><td>${status}</td><td>Discrete boolean, interpreted by signal role</td></tr>
    <tr><td>L1</td><td>Energy registers</td><td>${energy}</td><td>Float32 holding registers</td></tr>
  </tbody>
</table>

<h2>3 · Why counting happens at the edge</h2>
<p>The gateway polls at 100 ms and counts edges locally. A pulse that exists only between two server
polls is a pulse that would otherwise never be counted, and production figures that drop units during a
network blip are not figures anybody can act on. The gateway also buffers to disk, so a break in the
link to the platform delays the data without losing it.</p>

<h2>4 · How a state becomes a number</h2>
<table>
  <thead><tr><th>Step</th><th>Where</th><th>What happens</th></tr></thead>
  <tbody>
    <tr><td>1</td><td>L1 → L2</td><td>A discrete input is read and interpreted through its
      <b>signal role</b> — level, or rhythm for a pulsing signal.</td></tr>
    <tr><td>2</td><td>L2</td><td>Run Mode says the machine is <i>able</i> to work. A
      <b>Processing</b> signal says whether it <i>is</i>. Ready-but-idle is classified against the
      line as STARVED or BLOCKED, never guessed when there is no signal to support it.</td></tr>
    <tr><td>3</td><td>L2</td><td>A <b>state rule</b> decides what that state costs: whether it opens a
      downtime event, whether it is planned, which reason code it carries, and whether it is charged
      against OEE. Editable per factory and per machine.</td></tr>
    <tr><td>4</td><td>L2 → L3</td><td>The event and the counts are written to the platform;
      per-minute snapshots become the fact store the KPIs read.</td></tr>
    <tr><td>5</td><td>L3</td><td>External losses (STARVED / BLOCKED) are removed from planned production
      time <b>before</b> Availability and Performance are derived, so a machine is not punished for
      waiting on the line.</td></tr>
  </tbody>
</table>

<div class="note"><b>Nothing in steps 1–3 is compiled in.</b> Signal roles, pulse and idle thresholds,
state rules and alarm limits are all rows in the database, edited from the application or from the edge
gateway's own dashboard. That is deliberate: which contact means what, and what a stop costs, are plant
decisions — a customer should not need a redeploy to change one.</div>

<h2>5 · Resilience</h2>
<table>
  <thead><tr><th>Failure</th><th>Behaviour</th></tr></thead>
  <tbody>
    <tr><td>Platform unreachable</td><td>The gateway keeps polling, counting and evaluating alarms;
      readings buffer to disk and flush when the link returns.</td></tr>
    <tr><td>Gateway restarted mid-stop</td><td>Counter state is restored from disk; an open downtime or
      alarm event is adopted rather than duplicated.</td></tr>
    <tr><td>A sensor reads BAD quality</td><td>It is ignored for classification. Acting on a reading the
      gateway itself distrusts would put a wrong reason into the downtime log.</td></tr>
    <tr><td>A contact chatters</td><td>A configurable settling time per state prevents an event per poll.</td></tr>
  </tbody>
</table>`;

  return page(
    'Industrial Automation System Architecture',
    'Tracker ID 26 · L0 → L4, and how a contact becomes a KPI',
    body, now,
  );
}

async function main() {
  const data = await load();
  const now = new Date();
  mkdirSync(OUT_DIR, { recursive: true });

  const files: [string, string][] = [
    ['NCC-25-Instrumentation-Layout.html', instrumentationLayout(data, now)],
    ['NCC-26-Automation-Architecture.html', automationArchitecture(data, now)],
  ];
  for (const [name, html] of files) {
    const target = join(OUT_DIR, name);
    writeFileSync(target, html, 'utf8');
    console.log(`  wrote ${target} (${(html.length / 1024).toFixed(1)} kB)`);
  }
  console.log(`\n[drawings] ${data.machines.length} machines, ${data.devices.length} devices, ${data.tags.length} tags`);
}

main()
  .catch((e) => {
    console.error('[drawings] generation failed:', e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
